/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AgentDesignRouteImport } from './routes/agent-design'
import { Route as AgentWorkflowRouteImport } from './routes/agent-workflow'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesPostIdRouteImport } from './routes/messages.$postId'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDesignRoute = AgentDesignRouteImport.update({
  id: '/agent-design',
  path: '/agent-design',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentWorkflowRoute = AgentWorkflowRouteImport.update({
  id: '/agent-workflow',
  path: '/agent-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesPostIdRoute = MessagesPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => MessagesRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-design': typeof AgentDesignRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/plan': typeof PlanRoute
  '/saved': typeof SavedRoute
  '/messages/$postId': typeof MessagesPostIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-design': typeof AgentDesignRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/dashboard': typeof DashboardRoute
  '/plan': typeof PlanRoute
  '/saved': typeof SavedRoute
  '/messages/$postId': typeof MessagesPostIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-design': typeof AgentDesignRoute
  '/agent-workflow': typeof AgentWorkflowRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRouteWithChildren
  '/plan': typeof PlanRoute
  '/saved': typeof SavedRoute
  '/messages/$postId': typeof MessagesPostIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/agent-design'
    | '/agent-workflow'
    | '/dashboard'
    | '/messages'
    | '/plan'
    | '/saved'
    | '/messages/$postId'
    | '/people/$personId'
    | '/posts/$postId'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/agent-design'
    | '/agent-workflow'
    | '/dashboard'
    | '/plan'
    | '/saved'
    | '/messages/$postId'
    | '/people/$personId'
    | '/posts/$postId'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/agent-design'
    | '/agent-workflow'
    | '/dashboard'
    | '/messages'
    | '/plan'
    | '/saved'
    | '/messages/$postId'
    | '/people/$personId'
    | '/posts/$postId'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AgentDesignRoute: typeof AgentDesignRoute
  AgentWorkflowRoute: typeof AgentWorkflowRoute
  DashboardRoute: typeof DashboardRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PlanRoute: typeof PlanRoute
  SavedRoute: typeof SavedRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-design': {
      id: '/agent-design'
      path: '/agent-design'
      fullPath: '/agent-design'
      preLoaderRoute: typeof AgentDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-workflow': {
      id: '/agent-workflow'
      path: '/agent-workflow'
      fullPath: '/agent-workflow'
      preLoaderRoute: typeof AgentWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$postId': {
      id: '/messages/$postId'
      path: '/$postId'
      fullPath: '/messages/$postId'
      preLoaderRoute: typeof MessagesPostIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesPostIdRoute: typeof MessagesPostIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesPostIdRoute: MessagesPostIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AgentDesignRoute: AgentDesignRoute,
  AgentWorkflowRoute: AgentWorkflowRoute,
  DashboardRoute: DashboardRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PlanRoute: PlanRoute,
  SavedRoute: SavedRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
